services:
  - type: web
    name: functional-batch-interface
    runtime: node
    plan: free
    region: oregon
    rootDir: functional-batch-web
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    autoDeployTrigger: commit
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
